export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER_DECODED = "SET_CURRENT_USER_DECODED";
export const SET_CURRENT_USER = "SET_CURRENT_USER";